[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read", path = "./"}]
gas_reports = ["Wallet"]
[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
fantom-tst = "https://xapi.testnet.fantom.network/lachesis"
[etherscan]
fantom-tst = { key = "${FANTOM_API_KEY}" }
# See more config options https://github.com/foundry-rs/foundry/tree/master/config